/**
 * Iframe bridge: receives OpenAPI + history via postMessage from APIQuality.
 * Follows the same pattern as visual-mapper's MdFooter.vue.
 *
 * All data is exchanged in base64 to match visual-mapper convention.
 *
 * Receives a JSON message with:
 *   - openapi_b64:           OpenAPI spec in base64 (required)
 *   - history_b64:           Previous config JSON in base64 (optional, for re-editing)
 *   - api_quality_api_id:    APIQuality API ID (optional)
 *   - api_quality_branch_id: APIQuality branch ID (optional)
 *   - api_quality_org:       APIQuality organization (optional)
 *
 * Sends back to parent: base64-encoded JSON config string
 *
 * Exposes globals: iframeConfig
 * Depends on: nothing (loaded before app.js)
 */

var iframeConfig = null;

/**
 * Validates that the incoming message looks like an APIQuality iframe payload.
 */
function isIframePayload(data) {
  return data != null
    && typeof data === 'object'
    && typeof data.openapi_b64 === 'string'
    && data.type === undefined;
}

/**
 * Initialize the postMessage listener.
 * When a valid payload arrives, stores it in iframeConfig and triggers processing.
 */
function initIframeBridge() {
  window.addEventListener('message', function(event) {
    console.log('[iframe-bridge] message received:', event.data);
    if (!event || !event.data) return;
    if (!isIframePayload(event.data)) {
      console.log('[iframe-bridge] rejected: not a valid payload');
      return;
    }
    console.log('[iframe-bridge] valid payload, processing...');

    // Decode history from base64 if provided
    var historyObj = null;
    if (event.data.history_b64) {
      try {
        historyObj = JSON.parse(atob(event.data.history_b64));
      } catch (e) {
        console.error('Error decoding history_b64:', e);
      }
    }

    iframeConfig = {
      openapi_b64:           event.data.openapi_b64,
      history_json:          historyObj,
      api_quality_api_id:    event.data.api_quality_api_id || null,
      api_quality_branch_id: event.data.api_quality_branch_id || null,
      api_quality_org:       event.data.api_quality_org || null
    };

    processIframePayload();
  });
}

/**
 * Processes the received iframe payload:
 * 1. Decodes and parses the OpenAPI spec
 * 2. Fills the form with spec data
 * 3. If history_json exists, restores previous form state
 * 4. Hides the manual upload area
 */
function processIframePayload() {
  if (!iframeConfig || !iframeConfig.openapi_b64) return;

  try {
    var fileText = atob(iframeConfig.openapi_b64);
    var spec = fileText.trim().startsWith('{')
      ? JSON.parse(fileText)
      : jsyaml.load(fileText);

    parsedSpec = spec;
    fillFromSpec(spec);

    // Hide upload area and show iframe status
    var uploadArea = document.getElementById('uploadArea');
    if (uploadArea) uploadArea.style.display = 'none';

    var status = document.getElementById('uploadStatus');
    if (status) {
      status.style.display = 'block';
      status.textContent = '\u2713 OpenAPI loaded from APIQuality';
    }

    // Restore history if provided
    if (iframeConfig.history_json) {
      restoreFromHistory(iframeConfig.history_json);
    }
  } catch (err) {
    console.error('Error processing iframe payload:', err);
    var status = document.getElementById('uploadStatus');
    if (status) {
      status.style.display = 'block';
      status.style.color = 'red';
      status.textContent = '\u2717 Error parsing OpenAPI: ' + err.message;
    }
  }
}

/**
 * Restores form fields from a previously saved configuration (history_json).
 * This is the same JSON structure generated by buildConfig() / downloadConfig().
 */
function restoreFromHistory(history) {
  if (!history || typeof history !== 'object') return;

  // Provider fields
  if (history.provider) {
    var p = history.provider;
    if (p.did)       setField('f_issuer', p.did);
    if (p.legalName) setField('f_legalName', p.legalName);
    if (p.shortName) setField('f_orgName', p.shortName);
    if (p.country)   setField('f_country', p.country);
    if (p.registrationNumber) {
      if (p.registrationNumber.vatID)   setField('f_vatId', p.registrationNumber.vatID);
      if (p.registrationNumber.leiCode) setField('f_leiCode', p.registrationNumber.leiCode);
      if (p.registrationNumber.EORI)    setField('f_eoriCode', p.registrationNumber.EORI);
    }
    if (p.address) {
      if (p.address.street)     setField('f_street', p.address.street);
      if (p.address.postalCode) setField('f_postalCode', p.address.postalCode);
      if (p.address.city)       setField('f_city', p.address.city);
      if (p.address.regionCode) setField('f_regionCode', p.address.regionCode);
    }
    if (p.parentOrganization) setField('f_parentOrg', p.parentOrganization);
    if (p.compliance) {
      if (p.compliance.complianceLabel)      setField('f_complianceLabel', p.compliance.complianceLabel);
      if (p.compliance.trustFrameworkVersion) setField('f_trustFrameworkVersion', p.compliance.trustFrameworkVersion);
    }
  }

  // Software Resource fields
  if (history.softwareResource) {
    var sw = history.softwareResource;
    if (sw.vcId)               setField('f_vcId', sw.vcId);
    if (sw.credentialSubjectId) setField('f_credentialSubjectId', sw.credentialSubjectId);
    if (sw.issuanceDate)       setField('f_issuanceDate', sw.issuanceDate.slice(0, 16));
    if (sw.expirationDate)     setField('f_validUntil', sw.expirationDate.slice(0, 16));
    if (sw.name)               setField('f_name', sw.name);
    if (sw.description)        setField('f_description', sw.description);
    if (sw.version)            setField('f_version', sw.version);
    if (sw.license && sw.license[0]) setField('f_license', sw.license[0]);
    if (sw.copyrightOwner)     setField('f_copyrightOwner', sw.copyrightOwner);
    if (sw.contact) {
      if (sw.contact.email) setField('f_contactEmail', sw.contact.email);
      if (sw.contact.url)   setField('f_contactUrl', sw.contact.url);
    }
    if (sw.softwareReference)   setField('f_softwareRef', sw.softwareReference);
    if (sw.programmingLanguage) setField('f_progLang', sw.programmingLanguage);
    if (sw.checksum)            setField('f_checksum', sw.checksum);
    if (sw.format)              setField('f_resourceFormat', sw.format);
    if (sw.contract) {
      if (sw.contract.negotiationLink) setField('f_negotiationLink', sw.contract.negotiationLink);
      if (sw.contract.sla)             setField('f_slaUrl', sw.contract.sla);
    }
    if (sw.technicalInterface && sw.technicalInterface.endpoint) {
      setField('f_openApiBasePath', sw.technicalInterface.endpoint);
    }
  }

  // Service Offering fields
  if (history.serviceOffering) {
    var so = history.serviceOffering;
    if (so.vcId)       setField('f_serviceOfferingId', so.vcId);
    if (so.description) setField('f_serviceDesc', so.description);
    if (so.termsAndConditions) {
      if (so.termsAndConditions.url)  setField('f_termsUrl', so.termsAndConditions.url);
      if (so.termsAndConditions.hash) setField('f_termsHash', so.termsAndConditions.hash);
    }
    if (so.dataSovereignty) {
      if (so.dataSovereignty.dataLocation) setField('f_serviceDataLocation', so.dataSovereignty.dataLocation);
      if (so.dataSovereignty.isSovereign != null) setField('f_isSovereign', String(so.dataSovereignty.isSovereign));
    }
    if (so.complianceLabel && so.complianceLabel.level) {
      setField('f_serviceComplianceLevel', so.complianceLabel.level);
    }
  }

  // Data Resource fields
  if (history.dataResource) {
    var dr = history.dataResource;
    if (dr.vcId)            setField('f_dataResourceId', dr.vcId);
    if (dr.name)            setField('f_dataName', dr.name);
    if (dr.description)     setField('f_dataDescription', dr.description);
    if (dr.copyrightOwner)  setField('f_dataCopyrightOwner', dr.copyrightOwner);
    if (dr.license && dr.license[0]) setField('f_dataLicense', dr.license[0]);
    if (dr.containsPII != null) setField('f_containsPersonalData', String(dr.containsPII));
    if (dr.dataAccountability)  setField('f_dataAccountability', dr.dataAccountability);
    if (dr.privacy) {
      if (dr.privacy.processingBasis) setField('f_processingBasis', dr.privacy.processingBasis);
      if (dr.privacy.anonymization)   setField('f_anonymization', dr.privacy.anonymization);
    }
  }

  // Infrastructure Resource fields
  if (history.infrastructureResource) {
    var ir = history.infrastructureResource;
    if (ir.vcId)            setField('f_infraId', ir.vcId);
    if (ir.name)            setField('f_infraName', ir.name);
    if (ir.description)     setField('f_infraDesc', ir.description);
    if (ir.copyrightOwner)  setField('f_infraCopyrightOwner', ir.copyrightOwner);
    if (ir.license && ir.license[0]) setField('f_infraLicense', ir.license[0]);
    if (ir.nodeInfo) {
      if (ir.nodeInfo.serviceType)    setField('f_infraServiceType', ir.nodeInfo.serviceType);
      if (ir.nodeInfo.location)       setField('f_infraLocation', ir.nodeInfo.location);
      if (ir.nodeInfo.resourceType)   setField('f_infraResourceType', ir.nodeInfo.resourceType);
      if (ir.nodeInfo.databaseEngine) setField('f_dbEngine', ir.nodeInfo.databaseEngine);
    }
    if (ir.technicalAttributes) {
      if (ir.technicalAttributes.cpuCores)    setField('f_cpuCores', String(ir.technicalAttributes.cpuCores));
      if (ir.technicalAttributes.ramGb)       setField('f_ramGb', String(ir.technicalAttributes.ramGb));
      if (ir.technicalAttributes.storageType) setField('f_storageType', ir.technicalAttributes.storageType);
      if (ir.technicalAttributes.networkZone) setField('f_networkZone', ir.technicalAttributes.networkZone);
    }
  }

  // Contract Definition fields
  if (history.contractDefinition) {
    var cd = history.contractDefinition;
    if (cd.contractName) setField('f_contractName', cd.contractName);
    if (cd.contractId)   setField('f_contractId', cd.contractId);
    if (cd.status)       setField('f_contractStatus', cd.status);
    if (cd.offeringModel) setField('f_offeringModel', cd.offeringModel);
    if (cd.parties && cd.parties.consumer) setField('f_consumerDid', cd.parties.consumer);
    if (cd.serviceLevels) {
      cd.serviceLevels.forEach(function(sl) {
        if (sl.metric === 'availability')  setField('f_slaAvailability', String(sl.targetValue));
        if (sl.metric === 'latency_p95')   setField('f_slaLatency', String(sl.targetValue));
        if (sl.metric === 'rate_limit')    setField('f_slaRateLimit', String(sl.targetValue));
        if (sl.measurementWindow)          setField('f_slaWindow', sl.measurementWindow);
      });
    }
    if (cd.billing && cd.billing.model) setField('f_billingModel', cd.billing.model);
    if (cd.termination && cd.termination.noticePeriod) setField('f_noticePeriod', cd.termination.noticePeriod);
  }

  // EDC fields
  if (history.edc) {
    var edc = history.edc;
    if (edc.managementUrl) setField('f_edcUrl', edc.managementUrl);
    if (edc.apiKey)        setField('f_edcApiKey', edc.apiKey);
    if (edc.assetPrefix)   setField('f_assetPrefix', edc.assetPrefix);
    if (edc.contentType)   setField('f_contentType', edc.contentType);
    if (edc.protocol)      setField('f_edcProtocol', edc.protocol);
    if (edc.authType)      setField('f_authType', edc.authType);
  }

  // Policy fields
  if (history.policy) {
    var pol = history.policy;
    if (pol.legalFramework) {
      if (pol.legalFramework.governingLaw)  setField('f_governingLaw', pol.legalFramework.governingLaw);
      if (pol.legalFramework.arbitration)    setField('f_arbitration', pol.legalFramework.arbitration);
      if (pol.legalFramework.legalTemplate) setField('f_legalTemplate', pol.legalFramework.legalTemplate);
    }
    if (pol.mode === 'preset') {
      setPolicyMode('preset');
      if (pol.accessPolicyId)   setField('f_presetPolicy', pol.accessPolicyId);
      if (pol.contractPolicyId) setField('f_presetContractPolicy', pol.contractPolicyId === pol.accessPolicyId ? 'same' : pol.contractPolicyId);
    }
  }

  // Open all sections after restore
  document.querySelectorAll('.section').forEach(function(s) {
    s.classList.add('open');
    var t = s.querySelector('.section-toggle');
    if (t) t.textContent = '\u25BE';
  });
}

/**
 * Sends the generated config back to the parent window (APIQuality) as base64.
 * Called after successful generation/download.
 */
function sendResultToParent(configJson) {
  if (window.parent && window.parent !== window) {
    var b64 = btoa(unescape(encodeURIComponent(JSON.stringify(configJson))));
    var files = [
      { filename: 'edc-config.json', content_in_base64: b64 }
    ];
    window.parent.postMessage({ files: files }, '*');
  }
}
